/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Dialog: typeof import('./src/components/global/Dialog.vue')['default']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTag: typeof import('element-plus/es')['ElTag']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
